project:
  type: website
  output-dir: ../docs

website:
  title: "rmdmoodle"
  navbar:
    left:
      - href: index.qmd
        text: Principal
      - moodle.qmd
      - unico.qmd
      - base.qmd
      - examples.qmd
      - debug.qmd
      - sobre.qmd

permissions:
  id-token: write
  pages: write

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


  


