---
title: "Single test, Single file"
author: "Pedro Cruz"
date: "2024-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Question 1 - Estatística Descritiva - CLOZE


## Variante 1

Considere a amostra \(2.2, 5.6, 3.8\):

**(a)** A média amostral é {:NUMERICAL:=3.866667:0.005} (use 2 casas decimais).

**(b)** O valor máximo é {:NUMERICAL:=5.6}.

**(c)** A média é uma medida de 
{:MULTICHOICE_S:=localização central\~localização relativa\~dispersão}


### feedback

Consulte o Capítulo 1 - Estatística Descritiva.


## Variante 2

Considere a amostra \(2.2, 5.6, 1.1\):

**(a)** A média amostral é {:NUMERICAL:=2.966667:0.005} (use 2 casas decimais).

**(b)** O valor mínimo é {:NUMERICAL:=2.2}.

**(c)** O desvio padrão corrigido é uma medida de 
{:MULTICHOICE_S:=dispersão\~localização central\~localização relativa}


### feedback

Consulte o Capítulo 1 - Estatística Descritiva.


# Questão 2 - Natureza e escalas - MULTICHOICE


## Variante 01  

Seja "N.º diário de pagamentos numa loja de roupas" uma variável estatística. 
Esta é uma variável é

### Respostas  

* quantitativa, discreta, classificada em escala de razão.  
* qualitativa, classificada em escala ordinal.
* quantitativa, contínua, classificada em escala de intervalos.
* quantitativa, discreta, classificada em escala nominal.

### Feedback

Consulte o Capítulo 1 - Estatística Descritiva.

## Variante 02  


Seja "peso de uma enguia (em kg)" uma variável estatística. 
Esta é uma variável é

### Respostas  

* quantitativa, contínua, classificada em escala de razão.
* quantitativa, discreta, classificada em escala de intervalos.  
* qualitativa, classificada em escala ordinal.
* quantitativa, discreta, classificada em escala nominal.

### Feedback

Consulte o Capítulo 1 - Estatística Descritiva.